import {
  Activity,
  BookOpen,
  Box,
  Boxes,
  Building2,
  Calculator,
  Calendar,
  Car,
  ChartColumn,
  Clock,
  Cog,
  Container,
  CreditCard,
  Database,
  Download,
  Drama,
  EyeOff,
  FileText,
  Gauge,
  Globe,
  GraduationCap,
  HardDrive,
  Heart,
  Image,
  KeyRound,
  Landmark,
  Layers,
  ListOrdered,
  Lock,
  type LucideIcon,
  Mail,
  MapPin,
  MessageCircle,
  MonitorSmartphone,
  Package,
  Plane,
  Plug,
  Receipt,
  Search,
  Server,
  Settings2,
  Shield,
  ShieldCheck,
  ShoppingCart,
  Sigma,
  Star,
  Stethoscope,
  Store,
  Tag,
  Tags,
  Terminal,
  TriangleAlert,
  Truck,
  Upload,
  User,
  Users,
  Wallet,
  Waypoints,
  Webhook,
  Workflow,
  Zap,
  Bell,
} from "lucide-react"
import {
  siAdyen,
  siAlgolia,
  siAlpinelinux,
  siAngular,
  siAnthropic,
  siApache,
  siApachecassandra,
  siApachekafka,
  siApachemaven,
  siApachepulsar,
  siAuth0,
  siBraintree,
  siBun,
  siCelery,
  siClerk,
  siClickhouse,
  siCloudflare,
  siCockroachlabs,
  siCouchbase,
  siCurl,
  siDatadog,
  siDeno,
  siDiscord,
  siDjango,
  siDocker,
  siDotnet,
  siElasticsearch,
  siElixir,
  siExpress,
  siFastapi,
  siFastify,
  siFirebase,
  siFlask,
  siGit,
  siGithub,
  siGitlab,
  siGo,
  siGooglecloud,
  siGradle,
  siGraphql,
  siGunicorn,
  siHono,
  siHubspot,
  siInfluxdb,
  siIntercom,
  siJavascript,
  siJsonwebtokens,
  siKeycloak,
  siKlarna,
  siKoa,
  siKotlin,
  siKubernetes,
  siLaravel,
  siLinux,
  siMailchimp,
  siMailgun,
  siMariadb,
  siMeilisearch,
  siMercadopago,
  siMinio,
  siMongodb,
  siMqtt,
  siMysql,
  siNatsdotio,
  siNeo4j,
  siNestjs,
  siNextdotjs,
  siNginx,
  siNodedotjs,
  siNpm,
  siOkta,
  siOpenjdk,
  siPagseguro,
  siPaypal,
  siPhoenixframework,
  siPhp,
  siPix,
  siPodman,
  siPostgresql,
  siPrisma,
  siPython,
  siQuarkus,
  siRabbitmq,
  siReact,
  siRedis,
  siResend,
  siRuby,
  siRubyonrails,
  siRust,
  siScala,
  siSentry,
  siSequelize,
  siShopify,
  siSocketdotio,
  siSpringboot,
  siSqlite,
  siSquare,
  siStripe,
  siSupabase,
  siSwagger,
  siSymfony,
  siTelegram,
  siTerraform,
  siTypescript,
  siVercel,
  siVuedotjs,
  siWhatsapp,
  siZendesk,
} from "simple-icons"
import type { ActivityKind } from "../../../src/shared/types"

export type BrandIcon = { title: string; hex: string; path: string }

const BRANDS: Array<[string[], BrandIcon]> = [
  [["redis", "valkey"], siRedis],
  [["postgres", "postgresql", "pg", "psql", "pgx"], siPostgresql],
  [["mysql"], siMysql],
  [["mariadb"], siMariadb],
  [["mongo", "mongodb", "mongoose"], siMongodb],
  [["kafka", "apachekafka"], siApachekafka],
  [["rabbitmq", "amqp"], siRabbitmq],
  [["elasticsearch", "elastic", "opensearch"], siElasticsearch],
  [["express", "expressjs"], siExpress],
  [["node", "nodejs", "node.js"], siNodedotjs],
  [["go", "golang", "net/http"], siGo],
  [["python", "pip"], siPython],
  [["django"], siDjango],
  [["flask"], siFlask],
  [["fastapi", "uvicorn"], siFastapi],
  [["spring", "springboot", "spring-boot"], siSpringboot],
  [["java", "jvm", "openjdk"], siOpenjdk],
  [[".net", "dotnet", "csharp", "c#", "asp.net", "aspnet"], siDotnet],
  [["ruby"], siRuby],
  [["rails", "rubyonrails"], siRubyonrails],
  [["php"], siPhp],
  [["laravel"], siLaravel],
  [["symfony"], siSymfony],
  [["react"], siReact],
  [["vue", "vuejs"], siVuedotjs],
  [["angular"], siAngular],
  [["next", "nextjs", "next.js"], siNextdotjs],
  [["nginx"], siNginx],
  [["docker", "compose"], siDocker],
  [["kubernetes", "k8s"], siKubernetes],
  [["graphql", "apollo"], siGraphql],
  [["stripe"], siStripe],
  [["sqlite"], siSqlite],
  [["bun"], siBun],
  [["deno"], siDeno],
  [["rust"], siRust],
  [["typescript", "ts"], siTypescript],
  [["javascript", "js"], siJavascript],
  [["hono"], siHono],
  [["nestjs", "nest"], siNestjs],
  [["celery"], siCelery],
  [["git"], siGit],
  [["podman"], siPodman],
  [["swagger", "openapi"], siSwagger],
  [["jwt", "jsonwebtoken", "jsonwebtokens"], siJsonwebtokens],
  [["auth0"], siAuth0],
  [["minio", "s3"], siMinio],
  [["gcp", "googlecloud"], siGooglecloud],
  [["firebase"], siFirebase],
  [["supabase"], siSupabase],
  [["prisma"], siPrisma],
  [["sequelize"], siSequelize],
  [["kotlin"], siKotlin],
  [["scala"], siScala],
  [["elixir"], siElixir],
  [["phoenix"], siPhoenixframework],
  [["cassandra"], siApachecassandra],
  [["nats"], siNatsdotio],
  [["github"], siGithub],
  [["gitlab"], siGitlab],
  [["sentry"], siSentry],
  [["datadog"], siDatadog],
  [["paypal"], siPaypal],
  [["mailgun"], siMailgun],
  [["socket.io", "socketio", "websocket", "websockets"], siSocketdotio],
  [["gunicorn"], siGunicorn],
  [["koa"], siKoa],
  [["fastify"], siFastify],
  [["quarkus"], siQuarkus],
  [["cloudflare"], siCloudflare],
  [["terraform"], siTerraform],
  [["mqtt"], siMqtt],
  [["pulsar"], siApachepulsar],
  [["clickhouse"], siClickhouse],
  [["cockroachdb", "cockroach"], siCockroachlabs],
  [["influxdb"], siInfluxdb],
  [["neo4j"], siNeo4j],
  [["couchbase"], siCouchbase],
  [["meilisearch"], siMeilisearch],
  [["algolia"], siAlgolia],
  [["keycloak"], siKeycloak],
  [["okta"], siOkta],
  [["clerk"], siClerk],
  [["resend"], siResend],
  [["mailchimp"], siMailchimp],
  [["shopify"], siShopify],
  [["mercadopago"], siMercadopago],
  [["pagseguro"], siPagseguro],
  [["pix"], siPix],
  [["braintree"], siBraintree],
  [["adyen"], siAdyen],
  [["klarna"], siKlarna],
  [["square"], siSquare],
  [["hubspot"], siHubspot],
  [["zendesk"], siZendesk],
  [["intercom"], siIntercom],
  [["whatsapp"], siWhatsapp],
  [["telegram"], siTelegram],
  [["discord"], siDiscord],
  [["gradle"], siGradle],
  [["maven"], siApachemaven],
  [["npm"], siNpm],
  [["curl", "http"], siCurl],
  [["apache", "httpd"], siApache],
  [["anthropic", "claude"], siAnthropic],
  [["linux"], siLinux],
  [["alpine"], siAlpinelinux],
  [["vercel"], siVercel],
]

const LOOKUP = new Map<string, BrandIcon>(BRANDS.flatMap(([names, icon]) => names.map((n) => [n, icon] as const)))

export function brandIcon(tech?: string): BrandIcon | undefined {
  if (!tech) return undefined
  const key = tech.toLowerCase().trim()
  const direct = LOOKUP.get(key)
  if (direct) return direct
  const tokens = key.split(/[^a-z0-9.#+/]+/).filter(Boolean)
  for (const token of tokens) {
    const hit = LOOKUP.get(token) ?? LOOKUP.get(token.replace(/[0-9.]+$/, ""))
    if (hit) return hit
  }
  return undefined
}

/** Brand colors are designed for white pages; lift the dark ones so they read on ink. */
export function readableHex(hex: string) {
  const n = Number.parseInt(hex, 16)
  const [r, g, b] = [(n >> 16) & 255, (n >> 8) & 255, n & 255]
  const luminance = (0.2126 * r + 0.7152 * g + 0.0722 * b) / 255
  return luminance < 0.28 ? "#d5dbe7" : `#${hex}`
}

export const TARGET_TECH: Record<string, string> = { go: "go", typescript: "hono", python: "fastapi" }
export const TARGET_LABEL: Record<string, string> = { go: "Go", typescript: "TypeScript", python: "Python" }

export const MARKER_TECH: Record<string, string> = {
  node: "node",
  bun: "bun",
  deno: "deno",
  go: "go",
  java: "java",
  kotlin: "kotlin",
  python: "python",
  ruby: "ruby",
  php: "php",
  rust: "rust",
  elixir: "elixir",
  dotnet: "dotnet",
  docker: "docker",
  git: "git",
}

export const NODE_KINDS: Record<string, { icon: LucideIcon; color: string }> = {
  client: { icon: MonitorSmartphone, color: "#94a3b8" },
  gateway: { icon: Waypoints, color: "#c4b5fd" },
  service: { icon: Server, color: "#22d3ee" },
  module: { icon: Boxes, color: "#67e8f9" },
  worker: { icon: Cog, color: "#a78bfa" },
  datastore: { icon: Database, color: "#f5a524" },
  cache: { icon: Zap, color: "#fb7185" },
  queue: { icon: ListOrdered, color: "#f472b6" },
  external: { icon: Globe, color: "#34d399" },
  storage: { icon: HardDrive, color: "#fbbf24" },
}

export const DEPENDENCY_KINDS: Record<string, LucideIcon> = {
  database: Database,
  cache: Zap,
  queue: ListOrdered,
  "external-api": Globe,
  storage: HardDrive,
  search: Search,
  other: Box,
}

export const STRATEGIES: Record<string, { icon: LucideIcon; tone: "cyan" | "violet" | "slate" }> = {
  container: { icon: Container, tone: "cyan" },
  mock: { icon: Drama, tone: "violet" },
  skip: { icon: EyeOff, tone: "slate" },
}

export const RULE_KINDS: Record<string, { icon: LucideIcon; color: string }> = {
  validation: { icon: ShieldCheck, color: "#34d399" },
  calculation: { icon: Calculator, color: "#f5a524" },
  authorization: { icon: KeyRound, color: "#a78bfa" },
  state: { icon: Workflow, color: "#22d3ee" },
  persistence: { icon: Database, color: "#60a5fa" },
  integration: { icon: Plug, color: "#f472b6" },
  error: { icon: TriangleAlert, color: "#fb7185" },
  other: { icon: Sigma, color: "#94a3b8" },
}

const BATCH_ICONS: Record<string, LucideIcon> = {
  "shopping-cart": ShoppingCart,
  cart: ShoppingCart,
  checkout: ShoppingCart,
  "credit-card": CreditCard,
  payment: CreditCard,
  payments: CreditCard,
  receipt: Receipt,
  orders: Receipt,
  truck: Truck,
  shipping: Truck,
  bell: Bell,
  calendar: Calendar,
  mail: Mail,
  users: Users,
  user: User,
  "key-round": KeyRound,
  key: KeyRound,
  lock: Lock,
  auth: Lock,
  shield: Shield,
  package: Package,
  box: Box,
  tag: Tag,
  tags: Tags,
  store: Store,
  catalog: Store,
  wallet: Wallet,
  landmark: Landmark,
  "building-2": Building2,
  building: Building2,
  "book-open": BookOpen,
  "file-text": FileText,
  search: Search,
  settings: Settings2,
  cog: Cog,
  database: Database,
  layers: Layers,
  activity: Activity,
  health: Activity,
  "heart-pulse": Activity,
  "bar-chart": ChartColumn,
  "chart-column": ChartColumn,
  "message-circle": MessageCircle,
  globe: Globe,
  heart: Heart,
  star: Star,
  image: Image,
  upload: Upload,
  download: Download,
  webhook: Webhook,
  terminal: Terminal,
  clock: Clock,
  "map-pin": MapPin,
  "graduation-cap": GraduationCap,
  stethoscope: Stethoscope,
  plane: Plane,
  car: Car,
  zap: Zap,
  gauge: Gauge,
}

export function batchIcon(name?: string): LucideIcon {
  if (!name) return Layers
  const key = name
    .trim()
    .replace(/Icon$/, "")
    .replace(/([a-z0-9])([A-Z])/g, "$1-$2")
    .toLowerCase()
  return BATCH_ICONS[key] ?? BATCH_ICONS[key.split("-")[0]] ?? Layers
}

export const ACTIVITY_TONE: Record<ActivityKind, string> = {
  think: "text-violet-300 bg-violet-400/10",
  read: "text-sky-300 bg-sky-400/10",
  search: "text-cyan-300 bg-cyan-400/10",
  list: "text-cyan-300 bg-cyan-400/10",
  edit: "text-amber-300 bg-amber-400/10",
  write: "text-emerald-300 bg-emerald-400/10",
  bash: "text-slate-300 bg-white/5",
  web: "text-teal-300 bg-teal-400/10",
  todo: "text-violet-300 bg-violet-400/10",
  agent: "text-fuchsia-300 bg-fuchsia-400/10",
  text: "text-slate-200 bg-white/5",
  system: "text-slate-400 bg-white/5",
  success: "text-emerald-300 bg-emerald-400/10",
  error: "text-rose-300 bg-rose-400/10",
}
